#!/usr/bin/env bash
dark=$HOME/.config/kitty/EverforestDarkHard.conf
light=$HOME/.config/kitty/EverforestLightHard.conf


change_kitty_theme () {
  theme=$1
  ln -fs ${!theme} ~/.config/kitty/current-theme.conf
  for kitty_socket in /tmp/kitty_socket*; do
    kitty @ --to unix:"$kitty_socket" set-colors --all ~/.config/kitty/current-theme.conf
  done
}
#use theme passed as argument or toggle if none
if [[ -n $1 ]]; then
  theme=$1
else
  theme='dark'
  curr_theme=$(cat $HOME/.cache/theme)
  if [[ $curr_theme == 'dark' ]]; then
    theme='light'
  fi
fi
change_kitty_theme $theme
echo $theme > $HOME/.cache/theme
