allow_remote_control yes
listen_on unix:/tmp/kitty_socket
shell_integration no-cursor

font_family Hack Nerd Conf
font_size 11.0

enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
bell_on_tab no
notify_on_cmd_finish never

# _ is too far away 
map shift+space send_text normal,application _
map shit+inser past_from_selection
unmap shift+up
unmap shift+down

copy_on_select yes
clipboard_control write-clipboard write-primary no-append
confirm_os_window_close -1

paste_actions filter

include current-theme.conf
