allow_remote_control yes
listen_on unix:/tmp/kitty_socket
shell_integration no-cursor

font_family Hack Nerd Conf
font_size 11.0
include kitty-themes/themes/Wombat.conf

# _ is too far away 
map shift+space send_text normal,application _
map shit+inser past_from_selection
unmap shift+up
unmap shift+down

copy_on_select yes
clipboard_control write-clipboard write-primary no-append

paste_actions filter


# BEGIN_KITTY_THEME
# Hardcore
include current-theme.conf
# END_KITTY_THEME