# A port of everforest by sainnhe
# https://github.com/sainnhe/everforest

background  #fffbef
foreground  #5c6a72

cursor                #5c6a72
cursor_text_color     #fdf6e3

selection_foreground  #5c6a72
selection_background  #eaedc8

color0   #4a555b
color8   #525c62

# red
color1                #e668668
# light red
color9                #e66868

# green
color2                #8da101
# light green
color10               #8da101

# yellow
color3                #dfa000
# light yellow
color11               #dfa000

# blue
color4                #3a94c5
# light blue
color12               #3a94c5

# magenta
color5                #df69ba
# light magenta
color13               #df69ba

# cyan
color6                #35a77c
# light cyan
color14               #35a77c

# light gray
color7                #939f91
# dark gray
color15               #939f91
